services:
  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=epath
      - POSTGRES_USER=epath
      - POSTGRES_PASSWORD=epath
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U epath -d epath"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
