# Generated by Django 5.2.4 on 2025-07-14 11:53

import django.db.models.deletion
import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionnaireDefinition',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('version', models.CharField(default='1.0', max_length=20)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('release_date', models.DateField(auto_now_add=True)),
                ('definition', models.JSONField()),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('country', 'version'), name='uq_questionnaire_country_version')],
            },
        ),
        migrations.CreateModel(
            name='QuestionnaireRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_uuid', models.CharField(db_index=True, max_length=36)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('answers', models.JSONField()),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('in_progress', 'In Progress'), ('early_exited', 'Early Exited')], default='in_progress', max_length=20)),
                ('questionnaire_def_fk', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='questionnaire.questionnairedefinition')),
            ],
        ),
    ]
