# Generated by Django 5.2.4 on 2025-07-17 07:34

import django_jsonform.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0002_alter_questionnairedefinition_definition_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnairedefinition',
            name='definition',
            field=django_jsonform.models.fields.JSONField(blank=True, default=list, help_text='Define questionnaire as an array of category objects.'),
        ),
        migrations.AlterField(
            model_name='questionnairedefinition',
            name='id',
            field=models.CharField(editable=False, max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='questionnairerecord',
            name='answers',
            field=django_jsonform.models.fields.JSONField(blank=True, default=dict, help_text='Store questionnaire answers as a flat mapping of questionID→value'),
        ),
    ]
