# Generated by Django 5.2.4 on 2025-07-17 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatBotResponse',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_uuid', models.CharField(db_index=True, max_length=36)),
                ('llm_model', models.CharField(default='gpt-3.5-turbo', max_length=100)),
                ('response', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ChatUserMessage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_uuid', models.CharField(db_index=True, max_length=36)),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
    ]
